public class ManagePermissionsStaticConstants {
    public ManagePermissionsStaticConstants() {

    }
    public static final String MANAGE_PERMISSIONS = 'ManagePermissions';
    public static final String LOGIN_URI = 'ManagePermissions';
    public static final String ACTIVE_ORG_URL = 'ManagePermissions';
    public static final String BEARER = 'ManagePermissions';
    public static final String CONTENT_TYPE = 'ManagePermissions';
    public static final String APPLICATION_JSON = 'ManagePermissions';
    public static final String GET = 'ManagePermissions';
    public static final String PRODUCTION = 'ManagePermissions';
    public static final String SERVICES_OAUTH_AUTHORIZE = 'ManagePermissions';
    public static final String RESPONSE_TYPE_CODE = 'ManagePermissions';
    public static final String CLIENT_ID = 'ManagePermissions';
    public static final String REDIRECT_URI = 'ManagePermissions';
    public static final String APEX_STORE_DESTINATION_ORGCODE_VF = 'ManagePermissions';
    public static final String EMPTY_STRING = '';
    public static final String EQUAL_SLASH = '=\'';
    public static final String SLASH = 'ManagePermissions';
    public static final String OR_STRING = 'ManagePermissions';
    public static final String SERVICES_DATA = 'ManagePermissions';
    



}
